---
- hosts: all
  tasks:
  - apt: update_cache=yes name=mosh state=latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - yum: update_cache=yes name=mosh state=latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'