---
- hosts: all
  tasks:
  - apt: name=$item state=latest
    with_items:
      - mosh
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - yum: name=$item state=latest
    with_items:
      - mosh
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'