---
- hosts: all
  tasks:
  - name: Creates directory
    file:
      path: /var/prtg/scriptsxml
      state: directory
      owner: root
      group: root
      mode: 0775

  - name: Get the sctipt from Github (wget)
    get_url:
      url: 'https://raw.githubusercontent.com/dscalf23/scripts/master/SuperSensorV2.py'
      dest: /var/prtg/scriptsxml/SuperSensor.py
      mode: 0775
      force: yes

  - name: ubuntu | ensuring Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
    apt_repository:
      repo: "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"
      state: present
    when: ansible_distribution == 'Ubuntu'

  - name: Install EPEL repo.
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      state: present
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CloudLinux'

  - name: Import EPEL GPG key.
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
      state: present
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CloudLinux'

  - name: install on Ubuntu & Debian
    apt:
      update_cache: yes
      cache_valid_time: 0
      force_apt_get: yes
      name: "{{ aptpack }}"
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: install on centos
    yum:
      update_cache: yes
      name: "{{ yumpack }}"
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'CloudLinux'

  - pip: name=psutil
