---
- hosts: all
  tasks:
  - name: Creates directory
    file:
      path: /var/prtg/scriptsxml
      state: directory
      owner: root
      group: root
      mode: 0775

  - name: Get the sctipt from Github (wget) 
    get_url:
      url: 'https://raw.githubusercontent.com/dscalf23/scripts/master/SuperSensorV2.py'
      dest: /var/prtg/scriptsxml/SuperSensor.py
      mode: 0775
      force: yes

  - name: install on Ubuntu & Debian
    apt:
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      update_cache: yes
      name: "{{ aptpack }}"
      state: latest

  - name: install on centos
    yum:
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      update_cache: yes
      name: "{{ yumpack }}"
      state: latest  

  - pip:
    name: 'psutil'
